language: python
python: 3.5
sudo: false
addons:
  apt: 
  postgresql: '9.5'
env:
  matrix:
  - TOX_ENV=py35
  - TOX_ENV=kinto-master
  - TOX_ENV=flake8
  global:
  - secure: SZdf3p7TBW0T/MZ2ptTilt6UbEx25bxT4EXLn3aLtKAKqZh9phAUZ4QCms65g9MXXJWjbE87BHOUHStazyKgvp9TGCbOJM36hkALPYWTJFQymJpWTHGtYKGhfvJ7gRFo4Z6Ymbnip4sFwxVOlTlP+TtP4NEQFoRevci4GQz5VQj5f2x0hZtEf+14gSaZEF6JGYFvjSXn1aGDQjWvhowWgjt14aN0AWozO75bmnqRvi/MMApaJt3H8w5H/vA0AigUMQafy14bpeAN+pMDHxsdqiiwZLekmk7sHDFHbTZCv0cT7P4/0ynAxJ2T6KW62i8M0YBpFc/p/yThBVN3AquuIAAsf5RlACLoBdNQaGkopeqjU4fF4w2qS5N9xE6JqCZ3ZbhqPG1i3lTwGGmUVCJCdqL9o12H85ptpLufqSXpmBXQSDMtVhJi22sAjCZMmTFpjHeQ/qNbnLBkfFzZ/gBv8YRGAcvuBJRXxL/6g0uK+lqR9zbwZgNhgguw3nlQA9Eb9bc1XacnbQC3Je1nC8UTiJOFY2+l0hRPLeirxAlI5DxhX5PQmkuNIyohpLrx3UHUWXUDSOqe1sXj4LawOXpowqagGztuzv9CqC0dQZvQJmV9kkh4EgVT2718phS8wu5p3KZPvN07NdHe7jj/7hhMv6hSw7Wb6GcJEpV1ct+t/b4=
  - secure: m1zriBApPd8l+Ym+QrSGNt9aFWNwaaRRvhs4d6VtUqqpRLBVfdYV3KEN0u9zclcsxnDOzb53QPMQSCJVZfpnI+78yPrLjYKBxnbNlu8+pT3SATD7q3rc4KAT3HjQoe9LZR8CLdhTUL7QWf3rYUIbMwit4quMq5XatbisCn1p+iUcBK4PVziCUJxiNXFD1nEfnS5AMBgGcYFtG/aerMmysn9+8wLclw+55zWZVWtQNEvv0UFXd2cwBypikhHRACQeYiAby2blxl5GS8kR/nPgXyhfDag69rtsYtfikFAbngfuXlZrYRYq/iyQMS6IajW9Vic3sEobMCcwmQW++9Qek3tcphOeahc+usStLI/lCzZ3FDPpSUu8FKbQzttZB3rfPuOqq5RphCDxgXkjbxfdHX16FschyYdDB3O2rmvBeiCWH+oIWS/Ud99QL8729/9b0NRz79qcyfgj5PcTcwIpQmGS8fDzFhBmU3qdF+JUs+YnwAYlH4q0pSs4z2RGQhzgvjshzZ62KPNsWMv1A4h4p7FQ2GsjbNhn50BqJGwMYj+gaW+MO21LleBRM4lZPbq1cGZmBP9DLLzxHPoT59CA44pWoPoaLEdkpInVeJNEfx7eNz+TtaASpNkLZI/0KWcjzZL0f7OT50XRuhirtqs6X6+32XU0S4gBqoBvdKc/Y+c=
install: pip install -U tox
script: tox -e $TOX_ENV
after_success:
- pip install coveralls
- coveralls
